In [1]:
import pandas as pd

football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
display(football.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 42 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12897 non-null  int64
 1   Name             12897 non-null  object
 2   Age              12897 non-null  int64
 3   Nationality      12897 non-null  object
 4   Club             12897 non-null  object
 5   Value            12897 non-null  int64
 6   Wage             12897 non-null  int64
 7   Position         12897 non-null  object
 8   Crossing         12897 non-null  int64
 9   Finishing        12897 non-null  int64
 10  HeadingAccuracy  12897 non-null  int64
 11  ShortPassing     12897 non-null  int64
 12  Volleys          12897 non-null  int64
 13  Dribbling        12897 non-null  int64
 14  Curve            12897 non-null  int64
 15  FKAccuracy       12897 non-null  int64
 16  LongPassing      12897 non-null  int64
 17  BallControl      12897 non-null  int64
 18  Acceleration     12897 non-null  int64
 19  SprintSpeed      12897 non-null  int64
 20  Agility          12897 non-null  int64
 21  Reactions        12897 non-null  int64
 22  Balance          12897 non-null  int64
 23  ShotPower        12897 non-null  int64
 24  Jumping          12897 non-null  int64
 25  Stamina          12897 non-null  int64
 26  Strength         12897 non-null  int64
 27  LongShots        12897 non-null  int64
 28  Aggression       12897 non-null  int64
 29  Interceptions    12897 non-null  int64
 30  Positioning      12897 non-null  int64
 31  Vision           12897 non-null  int64
 32  Penalties        12897 non-null  int64
 33  Composure        12897 non-null  int64
 34  Marking          12897 non-null  int64
 35  StandingTackle   12897 non-null  int64
 36  SlidingTackle    12897 non-null  int64
 37  GKDiving         12897 non-null  int64
 38  GKHandling       12897 non-null  int64
 39  GKKicking        12897 non-null  int64
 40  GKPositioning    12897 non-null  int64
 41  GKReflexes       12897 non-null  int64
dtypes: int64(38), object(4)
memory usage: 4.1+ MB

None

In [5]:
import pandas as pd

football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.describe()

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,...,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,...,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,...,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,...,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,...,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,...,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,...,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,...,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [3]:
import pandas as pd

football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(football.describe())

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,44.264403,40.321625,50.115143,55.463596,63.109715,63.205629,61.819648,59.430565,63.171978,52.530666,64.285415,61.123052,64.271614,43.971931,53.777933,44.875940,47.166008,50.843374,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,17.781283,16.718481,15.215160,16.692643,15.129988,14.903845,14.858729,8.875832,14.190700,16.975214,11.765467,16.194498,12.550696,18.769749,17.232716,20.188799,19.245882,13.745960,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,6.000000,3.000000,9.000000,5.000000,12.000000,12.000000,15.000000,21.000000,16.000000,2.000000,15.000000,12.000000,17.000000,3.000000,11.000000,3.000000,2.000000,10.000000,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,32.000000,29.000000,40.000000,51.000000,55.000000,55.000000,53.000000,54.000000,55.000000,42.000000,57.000000,54.000000,57.000000,29.000000,41.000000,24.000000,35.000000,42.000000,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,45.000000,39.000000,53.000000,60.000000,66.000000,66.000000,64.000000,59.000000,65.000000,56.000000,65.000000,64.000000,65.000000,47.000000,56.000000,51.000000,52.000000,52.000000,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,58.000000,52.000000,61.000000,65.000000,74.000000,73.000000,72.000000,65.000000,73.000000,65.000000,72.000000,72.000000,73.000000,59.000000,67.000000,62.000000,61.000000,60.000000,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,93.000000,94.000000,93.000000,96.000000,97.000000,96.000000,96.000000,96.000000,96.000000,95.000000,95.000000,96.000000,97.000000,94.000000,95.000000,92.000000,95.000000,94.000000,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [49]:
import pandas as pd

football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football[(football.Composure>(football.Composure.max()*0.9))&(football.Reactions>(football.Reactions.max()*0.9))].Age.min()

24

In [69]:
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.sort_values(by='Age')

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9
12536,12765,F. Tauchhammer,16,Austria,Wolfsberger AC,90000,1000,RB,46,17,...,38,40,46,54,55,14,14,11,11,15
12439,12668,J. Olstad,16,Norway,Sarpsborg 08 FF,100000,1000,ST,28,53,...,54,42,13,19,20,7,8,9,11,8
12697,12926,J. Imbrechts,16,Sweden,Sporting de Charleroi,70000,1000,GK,9,4,...,18,27,6,15,12,55,49,53,45,56
8318,8509,Y. Verschaeren,16,Belgium,RSC Anderlecht,650000,1000,CAM,48,54,...,49,50,35,38,35,15,6,12,10,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,7184,H. Sulaimani,41,Saudi Arabia,Ohod Club,0,3000,LB,71,43,...,60,67,62,66,63,15,8,15,14,13
5394,5556,S. Narazaki,42,Japan,Nagoya Grampus,40000,1000,GK,23,11,...,11,45,27,24,22,64,63,62,67,63
12422,12651,T. Warner,44,Trinidad & Tobago,Accrington Stanley,0,1000,GK,19,13,...,17,46,19,15,14,48,56,56,60,44
12873,13102,K. Pilkington,44,England,Cambridge United,0,1000,GK,11,12,...,22,56,15,15,13,45,48,44,49,46
1628,1695,O. Pérez,45,Mexico,Pachuca,1300000,8000,GK,19,14,...,23,62,23,12,11,70,64,65,73,74

In [25]:
#Какова самая частая национальность (Nationality) футболистов?

import pandas as pd

football = pd.read_csv(r'C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Nationality[football.Value > football.Value.mean()].value_counts()

Spain                211
Brazil               130
France               123
Argentina            122
England              113
                    ...
Armenia                1
Mauritania             1
Comoros                1
Hungary                1
Equatorial Guinea      1
Name: Nationality, Length: 98, dtype: int64

In [15]:
import pandas as pd

football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Club[football.Value > football.Value.mean()].value_counts()

FC Barcelona              17
Manchester City           17
Liverpool                 17
Manchester United         17
West Ham United           17
                          ..
FC Dallas                  1
Vancouver Whitecaps FC     1
Queens Park Rangers        1
Al Ittihad                 1
Eintracht Braunschweig     1
Name: Club, Length: 447, dtype: int64

In [112]:
#1. Каково среднее значение возраста футболистов в наборе данных (округлите до целого)?
# неверно
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football[(football.Composure>(football.Composure.max()*0.9))&(football.Reactions>(football.Reactions.max()*0.9))].Age.min()

24

In [114]:
#5.6.2. Каков минимальный возраст футболиста?
#1. Каково среднее значение возраста футболистов в наборе данных (округлите до целого)?
#верно
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football['Age'].min()

16

In [115]:
#5.6.3. Какова максимальная заработная плата за год (Wage) у футболистов?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football['Wage'].max()

565000

#4. Какова медианная заработная плата за год (Wage) у футболистов?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football['Wage'].median()

In [61]:
#5.6.5. Каково минимальное значение параметра 'Penalties'?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football['Wage'].median()

2000.0

In [24]:
#5.6.6. Какое значение у первого (25%) квартиля параметра ShortPassing?

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.ShortPassing.quantile([0.25])

0.25    50.0
Name: ShortPassing, dtype: float64

In [62]:
#5.6.7.Какова самая частая национальность (Nationality) футболистов?

import pandas as pd

football = pd.read_csv(r'C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Nationality.value_counts()

England                 1368
Germany                  919
Spain                    671
France                   614
Argentina                574
                        ...
Central African Rep.       1
Botswana                   1
Guam                       1
Andorra                    1
Philippines                1
Name: Nationality, Length: 156, dtype: int64

In [59]:
#5.6.8. Сколько разных клубов в наборе данных о футболистах?
import pandas as pd

football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Club.value_counts()

Shonan Bellmare      30
V-Varen Nagasaki     30
Vissel Kobe          29
Padova               29
De Graafschap        29
                     ..
Cruzeiro              8
Dinamo Zagreb         7
Vitória Guimarães     7
GD Chaves             7
Atlético Mineiro      6
Name: Club, Length: 650, dtype: int64

In [57]:
#5.6.9. Сколько раз встречается самая частая позиция 'GK' в наборе данных?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Position.value_counts()

GK     1641
ST     1512
CB     1403
CM     1067
LB     1002
RB      948
RM      766
LM      728
CDM     691
CAM     633
RCB     418
LCB     409
LW      242
RCM     240
RW      237
LCM     233
LDM     148
RDM     138
LS      121
RS      114
RWB      70
LWB      60
CF       51
LF        8
LAM       6
RF        6
RAM       5
Name: Position, dtype: int64

In [58]:
#5.6.10. Каков максимальный возраст футболиста?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Age.max()

45

In [66]:
#5.7.2 2. Каково количество непустых строк в колонке Composure (Хладнокровие) набора данных о футболистах
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Composure.count()

12897

In [67]:
#5.7.3. Каково в наборе данных о футболистах 
#стандартное отклонение параметра коротких пасов (ShortPassing), округлённое до второго знака после запятой?

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
round(football.ShortPassing.std(),2)

14.74

In [68]:
#5.7.4. Какова сумма заработных плат за год (Wage) в наборе данных о футболистах?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Wage.sum()

96954000

In [69]:
#5.7.5. Какова минимальная стоимость футболиста (Value) в наборе данных о футболистах?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Value.min()

0

In [72]:
Как получить из DataFrame только нужные данные?

Часто возникает необходимость выбрать данные из DataFrame по определённому условию. Например, если в уже известном нам наборе данных о футболистах мы хотим выбрать только тех, у кого возраст больше 20 лет, используется следующий код:

import pandas as pd
football = pd.read_csv('/Users/maxim/Downloads/data_sf.csv')

football[football.Age > 20]

Синтаксис этой конструкции достаточно прост. Внутри квадратных скобок передается список из True или False, который показывает, какие строки DataFrame нужно оставить, а какие убрать. Этот список генерируется сравнением Series football.Age с 20. 

Можно для фильтрации использовать и методы получения статистических параметров. Например, если нам нужны только те футболисты, возраст которых больше среднего возраста футболистов, можно использовать следующую конструкцию:

football[football.Age > football.Age.mean()]

Условия можно и комбинировать, используя операторы & (логическое и) и | (логическое или). Условия при этом заключаются в скобки. Например, если мы хотим получить только тех футболистов, у которых возраст меньше среднего, или игроков 'FC Barcelona':

football[(football.Age < football.Age.mean())|
        (football.Club == 'FC Barcelona')]

Статистические параметры можно посчитать и по отфильтрованному DataFrame, например среднюю заработную плату футболистов с возрастом меньше среднего и из 'FC Barcelona':

football[(football.Age < football.Age.mean())&
        (football.Club == 'FC Barcelona')].Wage.mean()

Здесь мы получили среднюю годовую заработную плату футболистов из клуба FC Barcelona, возраст которых меньше среднего [возраста футболистов всех клубов].

SyntaxError: invalid syntax (<ipython-input-72-b92d61733cd9>, line 3)

In [74]:
#5.8.1. Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых выше среднего? Ответ округлите до сотых.

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
round(football[football.Wage > football.Wage.mean()].SprintSpeed.mean(),2)

67.57

In [75]:
#5.8.2. Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых выше среднего? Ответ округлите до сотых.
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
round(football[football.Wage < football.Wage.mean()].SprintSpeed.mean(),2)

62.41

In [76]:
#5.8.3. Какую позицию (Position) занимает футболист с самой высокой зарплатой (Wage)?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football[football.Wage == football.Wage.max()].Position

0    RF
Name: Position, dtype: object

In [2]:
#5.8.4. Сколько пенальти (Penalties) забили бразильские (Nationality, Brazil) 
# футболисты за период, данные о котором представлены в датасете?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football[football.Nationality == 'Brazil'].Penalties.sum()

22789

In [11]:
#5.8.5 Укажите средний возраст (Age) игроков, у которых точность удара головой (HeadingAccuracy) > 50. 
#Ответ округлите до сотых.

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
round(football[(football.HeadingAccuracy > 50)].Age.mean(),2)

25.59

In [10]:
#5.8.6  Укажите возраст (Age) самого молодого игрока, у которого хладнокровие (Composure) и реакция (Reactions) 
#превышают 90% от максимального значения, представленного в датасете.

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football[(football.Composure > 90/100*football.Composure.max())& (football.Reactions > 90/100*football.Reactions.max())].Age.min()

24

In [48]:
#5.8.7 #Определите, на сколько средняя реакция (Reactions) самых взрослых игроков 
#(т.е. игроков, чей возраст (Age) равен максимальному) больше средней реакции самых молодых игроков. 
#Ответ округлите до сотых.

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
old_reactions = football.Reactions[football.Age.max()].mean()
young_reactions = football.Reactions[football.Age.min()].mean()
display(young_reactions - old_reactions)

10.0

In [56]:
#5.8.8  Из какой страны (Nationality) происходит больше всего игроков, чья стоимость (Value) превышает среднее значение?
import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
football.Nationality[football.Value > football.Value.mean()].value_counts()

Spain         211
Brazil        130
France        123
Argentina     122
England       113
             ...
Haiti           1
Tanzania        1
Cyprus          1
Moldova         1
Mauritania      1
Name: Nationality, Length: 98, dtype: int64

In [46]:
#5.8.9 Определите, во сколько раз средняя зарплата (Wage) голкипера (Position, GK) с максимальным значением показателя 
#" Рефлексы" (GKReflexes) выше средней зарплаты голкипера с максимальным значением показателя 
#"Владение мячом" (GKHandling). Ответ округлите до сотых.

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
GK_R = football.Wage[(football.GKReflexes == football.GKReflexes.max()) & (football.Position == 'GK')].mean()
GK_H = football.Wage[(football.GKHandling == football.GKHandling.max()) & (football.Position == 'GK')].mean()
display(round((GK_R/GK_H),2))

2.77

In [50]:
#5.8.10 Определите, во сколько раз средняя сила удара (ShotPower) самых агрессивных игроков (игроков с максимальным значением показателя "Агрессивность" (Aggression)) выше средней силы удара игроков с минимальной агрессией. 
#Ответ округлите до сотых.

import pandas as pd
football = pd.read_csv('file:///C:/Users/syachin/01-Skillfactory/Sources/data_sf.csv')
P_Max = football.ShotPower[football.Aggression == football.Aggression.max()].mean()
P_Min = football.ShotPower[football.Aggression == football.Aggression.min()].mean()
display(round((P_Max/P_Min),2))

2.08